export const postings = [
  {
    title: "Software Developer, Intern",
    company: "Apple",
    type: "Internship",
    duration: "4 Months",
    location: "Remote",
    status: "Applied",
    logo: "https://www.edigitalagency.com.au/wp-content/uploads/apple-logo-png-black.png",
    saved: false,
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis varius quam quisque id. Velit egestas dui id ornare arcu odio. Elementum integer enim neque volutpat ac tincidunt. Sit amet nisl suscipit adipiscing bibendum est. Vulputate enim nulla aliquet porttitor lacus. Mi quis hendrerit dolor magna eget. Curabitur vitae nunc sed velit dignissim sodales ut eu sem. Imperdiet dui accumsan sit amet. Quisque non tellus orci ac auctor augue mauris. Ut morbi tincidunt augue interdum velit euismod in. Eu lobortis elementum nibh tellus molestie nunc. Eget arcu dictum varius duis at consectetur lorem. Nullam ac tortor vitae purus faucibus. Ac tincidunt vitae semper quis. Arcu dictum varius duis at consectetur lorem donec.",
      "thing 1",
      "thing 2",
      "thing 3",
      "Porta lorem mollis aliquam ut porttitor leo. Varius vel pharetra vel turpis nunc. Enim praesent elementum facilisis leo vel fringilla est. Tortor id aliquet lectus proin. Mi eget mauris pharetra et ultrices neque ornare. Maecenas accumsan lacus vel facilisis. Vitae purus faucibus ornare suspendisse sed. Massa tempor nec feugiat nisl pretium fusce id. In cursus turpis massa tincidunt dui ut ornare. In nulla posuere sollicitudin aliquam ultrices. Sit amet aliquam id diam maecenas ultricies. Viverra maecenas accumsan lacus vel facilisis volutpat est velit egestas. Orci a scelerisque purus semper eget duis. Tempus urna et pharetra pharetra. Libero nunc consequat interdum varius sit. Suspendisse sed nisi lacus sed. A lacus vestibulum sed arcu non odio.",
    ],
  },
  {
    title: "Data Scientist, Intern",
    company: "Scotiabank",
    type: "Internship",
    duration: "8 Months",
    location: "Toronto, ON",
    status: "Applied",
    logo: "https://seeklogo.com/images/S/scotiabank-logo-D2F1AF87B5-seeklogo.com.png",
    saved: false,
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis varius quam quisque id. Velit egestas dui id ornare arcu odio. Elementum integer enim neque volutpat ac tincidunt. Sit amet nisl suscipit adipiscing bibendum est. Vulputate enim nulla aliquet porttitor lacus. Mi quis hendrerit dolor magna eget. Curabitur vitae nunc sed velit dignissim sodales ut eu sem. Imperdiet dui accumsan sit amet. Quisque non tellus orci ac auctor augue mauris. Ut morbi tincidunt augue interdum velit euismod in. Eu lobortis elementum nibh tellus molestie nunc. Eget arcu dictum varius duis at consectetur lorem. Nullam ac tortor vitae purus faucibus. Ac tincidunt vitae semper quis. Arcu dictum varius duis at consectetur lorem donec.",
      "thing 1",
      "thing 2",
      "thing 3",
      "Porta lorem mollis aliquam ut porttitor leo. Varius vel pharetra vel turpis nunc. Enim praesent elementum facilisis leo vel fringilla est. Tortor id aliquet lectus proin. Mi eget mauris pharetra et ultrices neque ornare. Maecenas accumsan lacus vel facilisis. Vitae purus faucibus ornare suspendisse sed. Massa tempor nec feugiat nisl pretium fusce id. In cursus turpis massa tincidunt dui ut ornare. In nulla posuere sollicitudin aliquam ultrices. Sit amet aliquam id diam maecenas ultricies. Viverra maecenas accumsan lacus vel facilisis volutpat est velit egestas. Orci a scelerisque purus semper eget duis. Tempus urna et pharetra pharetra. Libero nunc consequat interdum varius sit. Suspendisse sed nisi lacus sed. A lacus vestibulum sed arcu non odio.",
    ],
  },
  {
    title: "Software Engineer",
    company: "Amazon",
    type: "New Grad",
    duration: null,
    location: "Vancouver, BC",
    status: "Applied",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Amazon_icon.svg/1200px-Amazon_icon.svg.png",
    saved: false,
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis varius quam quisque id. Velit egestas dui id ornare arcu odio. Elementum integer enim neque volutpat ac tincidunt. Sit amet nisl suscipit adipiscing bibendum est. Vulputate enim nulla aliquet porttitor lacus. Mi quis hendrerit dolor magna eget. Curabitur vitae nunc sed velit dignissim sodales ut eu sem. Imperdiet dui accumsan sit amet. Quisque non tellus orci ac auctor augue mauris. Ut morbi tincidunt augue interdum velit euismod in. Eu lobortis elementum nibh tellus molestie nunc. Eget arcu dictum varius duis at consectetur lorem. Nullam ac tortor vitae purus faucibus. Ac tincidunt vitae semper quis. Arcu dictum varius duis at consectetur lorem donec.",
      "thing 1",
      "thing 2",
      "thing 3",
      "Porta lorem mollis aliquam ut porttitor leo. Varius vel pharetra vel turpis nunc. Enim praesent elementum facilisis leo vel fringilla est. Tortor id aliquet lectus proin. Mi eget mauris pharetra et ultrices neque ornare. Maecenas accumsan lacus vel facilisis. Vitae purus faucibus ornare suspendisse sed. Massa tempor nec feugiat nisl pretium fusce id. In cursus turpis massa tincidunt dui ut ornare. In nulla posuere sollicitudin aliquam ultrices. Sit amet aliquam id diam maecenas ultricies. Viverra maecenas accumsan lacus vel facilisis volutpat est velit egestas. Orci a scelerisque purus semper eget duis. Tempus urna et pharetra pharetra. Libero nunc consequat interdum varius sit. Suspendisse sed nisi lacus sed. A lacus vestibulum sed arcu non odio.",
    ],
  },
  {
    title: "Software Engineer",
    company: "Apple",
    type: "New Grad",
    duration: null,
    location: "Remote",
    status: "",
    logo: "https://www.edigitalagency.com.au/wp-content/uploads/apple-logo-png-black.png",
    saved: true,
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis varius quam quisque id. Velit egestas dui id ornare arcu odio. Elementum integer enim neque volutpat ac tincidunt. Sit amet nisl suscipit adipiscing bibendum est. Vulputate enim nulla aliquet porttitor lacus. Mi quis hendrerit dolor magna eget. Curabitur vitae nunc sed velit dignissim sodales ut eu sem. Imperdiet dui accumsan sit amet. Quisque non tellus orci ac auctor augue mauris. Ut morbi tincidunt augue interdum velit euismod in. Eu lobortis elementum nibh tellus molestie nunc. Eget arcu dictum varius duis at consectetur lorem. Nullam ac tortor vitae purus faucibus. Ac tincidunt vitae semper quis. Arcu dictum varius duis at consectetur lorem donec.",
      "thing 1",
      "thing 2",
      "thing 3",
      "Porta lorem mollis aliquam ut porttitor leo. Varius vel pharetra vel turpis nunc. Enim praesent elementum facilisis leo vel fringilla est. Tortor id aliquet lectus proin. Mi eget mauris pharetra et ultrices neque ornare. Maecenas accumsan lacus vel facilisis. Vitae purus faucibus ornare suspendisse sed. Massa tempor nec feugiat nisl pretium fusce id. In cursus turpis massa tincidunt dui ut ornare. In nulla posuere sollicitudin aliquam ultrices. Sit amet aliquam id diam maecenas ultricies. Viverra maecenas accumsan lacus vel facilisis volutpat est velit egestas. Orci a scelerisque purus semper eget duis. Tempus urna et pharetra pharetra. Libero nunc consequat interdum varius sit. Suspendisse sed nisi lacus sed. A lacus vestibulum sed arcu non odio.",
    ],
  },
  {
    title: "Product Manager, Intern",
    company: "Duolingo",
    type: "Internship",
    duration: "4 Months",
    location: "Remote",
    status: "",
    logo: "https://www.langoly.com/wp-content/uploads/2020/03/Duolingo-app-icon.png",
    saved: true,
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis varius quam quisque id. Velit egestas dui id ornare arcu odio. Elementum integer enim neque volutpat ac tincidunt. Sit amet nisl suscipit adipiscing bibendum est. Vulputate enim nulla aliquet porttitor lacus. Mi quis hendrerit dolor magna eget. Curabitur vitae nunc sed velit dignissim sodales ut eu sem. Imperdiet dui accumsan sit amet. Quisque non tellus orci ac auctor augue mauris. Ut morbi tincidunt augue interdum velit euismod in. Eu lobortis elementum nibh tellus molestie nunc. Eget arcu dictum varius duis at consectetur lorem. Nullam ac tortor vitae purus faucibus. Ac tincidunt vitae semper quis. Arcu dictum varius duis at consectetur lorem donec.",
      "thing 1",
      "thing 2",
      "thing 3",
      "Porta lorem mollis aliquam ut porttitor leo. Varius vel pharetra vel turpis nunc. Enim praesent elementum facilisis leo vel fringilla est. Tortor id aliquet lectus proin. Mi eget mauris pharetra et ultrices neque ornare. Maecenas accumsan lacus vel facilisis. Vitae purus faucibus ornare suspendisse sed. Massa tempor nec feugiat nisl pretium fusce id. In cursus turpis massa tincidunt dui ut ornare. In nulla posuere sollicitudin aliquam ultrices. Sit amet aliquam id diam maecenas ultricies. Viverra maecenas accumsan lacus vel facilisis volutpat est velit egestas. Orci a scelerisque purus semper eget duis. Tempus urna et pharetra pharetra. Libero nunc consequat interdum varius sit. Suspendisse sed nisi lacus sed. A lacus vestibulum sed arcu non odio.",
    ],
  },
  {
    title: "Data Scientist, Intern",
    company: "Meta",
    type: "Internship",
    duration: "4 Months",
    location: "Remote",
    status: "",
    logo: "https://1000logos.net/wp-content/uploads/2021/10/logo-Meta.png",
    saved: false,
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis varius quam quisque id. Velit egestas dui id ornare arcu odio. Elementum integer enim neque volutpat ac tincidunt. Sit amet nisl suscipit adipiscing bibendum est. Vulputate enim nulla aliquet porttitor lacus. Mi quis hendrerit dolor magna eget. Curabitur vitae nunc sed velit dignissim sodales ut eu sem. Imperdiet dui accumsan sit amet. Quisque non tellus orci ac auctor augue mauris. Ut morbi tincidunt augue interdum velit euismod in. Eu lobortis elementum nibh tellus molestie nunc. Eget arcu dictum varius duis at consectetur lorem. Nullam ac tortor vitae purus faucibus. Ac tincidunt vitae semper quis. Arcu dictum varius duis at consectetur lorem donec.",
      "thing 1",
      "thing 2",
      "thing 3",
      "Porta lorem mollis aliquam ut porttitor leo. Varius vel pharetra vel turpis nunc. Enim praesent elementum facilisis leo vel fringilla est. Tortor id aliquet lectus proin. Mi eget mauris pharetra et ultrices neque ornare. Maecenas accumsan lacus vel facilisis. Vitae purus faucibus ornare suspendisse sed. Massa tempor nec feugiat nisl pretium fusce id. In cursus turpis massa tincidunt dui ut ornare. In nulla posuere sollicitudin aliquam ultrices. Sit amet aliquam id diam maecenas ultricies. Viverra maecenas accumsan lacus vel facilisis volutpat est velit egestas. Orci a scelerisque purus semper eget duis. Tempus urna et pharetra pharetra. Libero nunc consequat interdum varius sit. Suspendisse sed nisi lacus sed. A lacus vestibulum sed arcu non odio.",
    ],
  },
];
